version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=gotest
        - MONGO_INITDB_DATABASE=gotest
    volumes:
      - ./data:/data/db
      - ./seed.js:/docker-entrypoint-initdb.d/seed.js
